/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.cex.model;

import java.io.Serializable;

import net.sf.oval.constraint.Length;
import net.sf.oval.constraint.Min;
import net.sf.oval.constraint.NotEmpty;
import net.sf.oval.constraint.NotNull;
import net.sf.oval.constraint.Range;

/**
 * CardTransaction definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 04/01/2016.
 */
public class CardTransaction implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for transactionId. */
    @NotNull
    @NotEmpty
    @Length(max = 50)
    private String transactionId;

    /** Value for cardNo. */
    @NotNull
    @NotEmpty
    @Length(max = 30)
    private String cardNo;

    /** Value for cardUpc. */
    @NotNull
    @NotEmpty
    @Length(max = 15)
    private String cardUpc;

    /** Value for type. */
    @Min(100)
    private int type;

    /** Value for loadValue. */
    @Range (min=0, max=1000)
    private Double loadValue;

    /** Value for channelId. */
    @Min(100)
    private Integer channelId;

    /** Value for transactionTime. */
    private java.sql.Timestamp transactionTime;

    /** Value for remark. */
    private String remark;

    /**
     * Empty constructor.
     */
    public CardTransaction() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public CardTransaction(
        String transactionId,
        String cardNo,
        String cardUpc,
        int type,
        Double loadValue,
        Integer channelId,
        java.sql.Timestamp transactionTime,
        String remark
    ) {
        this.transactionId = transactionId;
        this.cardNo = cardNo;
        this.cardUpc = cardUpc;
        this.type = type;
        this.loadValue = loadValue;
        this.channelId = channelId;
        this.transactionTime = transactionTime;
        this.remark = remark;
    }

    /**
     * Gets transactionId.
     *
     * @return Value for transactionId.
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets transactionId.
     *
     * @param transactionId New value for transactionId.
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Gets cardNo.
     *
     * @return Value for cardNo.
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * Sets cardNo.
     *
     * @param cardNo New value for cardNo.
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * Gets cardUpc.
     *
     * @return Value for cardUpc.
     */
    public String getCardUpc() {
        return cardUpc;
    }

    /**
     * Sets cardUpc.
     *
     * @param cardUpc New value for cardUpc.
     */
    public void setCardUpc(String cardUpc) {
        this.cardUpc = cardUpc;
    }

    /**
     * Gets type.
     *
     * @return Value for type.
     */
    public int getType() {
        return type;
    }

    /**
     * Sets type.
     *
     * @param type New value for type.
     */
    public void setType(int type) {
        this.type = type;
    }

    /**
     * Gets loadValue.
     *
     * @return Value for loadValue.
     */
    public Double getLoadValue() {
        return loadValue;
    }

    /**
     * Sets loadValue.
     *
     * @param loadValue New value for loadValue.
     */
    public void setLoadValue(Double loadValue) {
        this.loadValue = loadValue;
    }

    /**
     * Gets channelId.
     *
     * @return Value for channelId.
     */
    public Integer getChannelId() {
        return channelId;
    }

    /**
     * Sets channelId.
     *
     * @param channelId New value for channelId.
     */
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    /**
     * Gets transactionTime.
     *
     * @return Value for transactionTime.
     */
    public java.sql.Timestamp getTransactionTime() {
        return transactionTime;
    }

    /**
     * Sets transactionTime.
     *
     * @param transactionTime New value for transactionTime.
     */
    public void setTransactionTime(java.sql.Timestamp transactionTime) {
        this.transactionTime = transactionTime;
    }

    /**
     * Gets remark.
     *
     * @return Value for remark.
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets remark.
     *
     * @param remark New value for remark.
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof CardTransaction))
            return false;

        CardTransaction that = (CardTransaction)o;

        if (transactionId != null ? !transactionId.equals(that.transactionId) : that.transactionId != null)
            return false;

        if (cardNo != null ? !cardNo.equals(that.cardNo) : that.cardNo != null)
            return false;

        if (cardUpc != null ? !cardUpc.equals(that.cardUpc) : that.cardUpc != null)
            return false;

        if (type != that.type)
            return false;

        if (loadValue != null ? !loadValue.equals(that.loadValue) : that.loadValue != null)
            return false;

        if (channelId != null ? !channelId.equals(that.channelId) : that.channelId != null)
            return false;

        if (transactionTime != null ? !transactionTime.equals(that.transactionTime) : that.transactionTime != null)
            return false;

        if (remark != null ? !remark.equals(that.remark) : that.remark != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = transactionId != null ? transactionId.hashCode() : 0;

        res = 31 * res + (cardNo != null ? cardNo.hashCode() : 0);

        res = 31 * res + (cardUpc != null ? cardUpc.hashCode() : 0);

        res = 31 * res + type;

        res = 31 * res + (loadValue != null ? loadValue.hashCode() : 0);

        res = 31 * res + (channelId != null ? channelId.hashCode() : 0);

        res = 31 * res + (transactionTime != null ? transactionTime.hashCode() : 0);

        res = 31 * res + (remark != null ? remark.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "CardTransaction [transactionId=" + transactionId +
            ", cardNo=" + cardNo +
            ", cardUpc=" + cardUpc +
            ", type=" + type +
            ", loadValue=" + loadValue +
            ", channelId=" + channelId +
            ", transactionTime=" + transactionTime +
            ", remark=" + remark +
            "]";
    }
}

