/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.cex.model;

import java.io.*;

/**
 * CardKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 03/10/2016.
 */
public class CardKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for cardId. */
    private String cardId;

    /**
     * Empty constructor.
     */
    public CardKey() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public CardKey(
        String cardId
    ) {
        this.cardId = cardId;
    }

    /**
     * Gets cardId.
     *
     * @return Value for cardId.
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * Sets cardId.
     *
     * @param cardId New value for cardId.
     */
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof CardKey))
            return false;

        CardKey that = (CardKey)o;

        if (cardId != null ? !cardId.equals(that.cardId) : that.cardId != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = cardId != null ? cardId.hashCode() : 0;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "CardKey [cardId=" + cardId +
            "]";
    }
}

