/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.cex.model;

import java.io.*;

/**
 * CardTransactionKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 04/01/2016.
 */
public class CardTransactionKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for transactionId. */
    private String transactionId;

    /**
     * Empty constructor.
     */
    public CardTransactionKey() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public CardTransactionKey(
        String transactionId
    ) {
        this.transactionId = transactionId;
    }

    /**
     * Gets transactionId.
     *
     * @return Value for transactionId.
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets transactionId.
     *
     * @param transactionId New value for transactionId.
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof CardTransactionKey))
            return false;

        CardTransactionKey that = (CardTransactionKey)o;

        if (transactionId != null ? !transactionId.equals(that.transactionId) : that.transactionId != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = transactionId != null ? transactionId.hashCode() : 0;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "CardTransactionKey [transactionId=" + transactionId +
            "]";
    }
}

